import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// This is the required placeholder for the manifest
self.__WB_MANIFEST;

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Supabase API requests
registerRoute(
  ({ url }) => url.origin === 'https://api.supabase.co',
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    networkTimeoutSeconds: 10
  })
);

// Cache static assets
registerRoute(
  ({ request }) => request.destination === 'style' || 
                  request.destination === 'script' ||
                  request.destination === 'image',
  new NetworkFirst({
    cacheName: 'static-assets-cache'
  })
);

// Handle service worker updates
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
}); 